graph LR
    1 --> |4| 2
    1 --> |2| 3
    2 --> |5| 4
    2 --> |1| 5
    3 --> |3| 6
    
    %% Node styles
    style 1 fill:#f9f,stroke:#333,stroke-width:2px
    style 2 fill:#bbf,stroke:#333,stroke-width:2px
    style 3 fill:#bbf,stroke:#333,stroke-width:2px
    style 4 fill:#ddf,stroke:#333,stroke-width:2px
    style 5 fill:#ddf,stroke:#333,stroke-width:2px
    style 6 fill:#ddf,stroke:#333,stroke-width:2px
